[package]
name = "derive"
version = "0.0.1"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.11"
syn = "0.15.29"
merklemountainrange= {path = "../../infrastructure/merklemountainrange"}
blake2 = "0.8.0"
proc-macro2 =   "0.4.27"
serde = "1.0.89"
bincode = "1.1.2"
serde_derive = "1.0.89"
