[package]
name = "blockchain"
version = "0.0.1"
edition = "2018"

[dependencies]
tari_core = { path = "../core"}
merklemountainrange= {path = "../../infrastructure/merklemountainrange"}
derive-error = "0.0.4"
blake2 = "0.8.0"
