[package]
name = "keymanager"
version = "0.0.1"

[dependencies]
crypto = { path = "../../infrastructure/crypto"}
rand = "0.5.5"
sha2 = "0.8.0"
derive-error = "0.0.4"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"

